version: "3.8"

services:
  user_postgres:
    image: postgres:15
    container_name: user_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data


  team_postgres:
    image: postgres:15
    container_name: team_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: team
    ports:
      - "5433:5432"
    volumes:
      - postgres_team_data:/var/lib/postgresql/data

  asset_postgres:
    image: postgres:15
    container_name: asset_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: asset
    ports:
      - "5434:5432"
    volumes:
      - postgres_asset_data:/var/lib/postgresql/data

volumes:
  postgres_user_data:
  postgres_team_data:
  postgres_asset_data:
