server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: user-service
    static_configs:
      - targets:
          - localhost
        labels:
          job: user-service
          __path__: /var/log/go-app/*.log
    pipeline_stages:
      - replace:
          expression: "\x00"
          replace: ""

      - timestamp:
          source: ts
          format: RFC3339
          action_on_failure: skip

      - labels:
          level:
          service:
          url:

      - output:
          source: msg
