auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 168h          # giữ log 7 ngày
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32     # <-- ĐÚNG, thay cho ingestion_burst_mb

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

ruler:
  enable_api: true
  alertmanager_url: http://localhost:9093
  storage:
    type: local
    local:
      directory: /loki/rules
  ring:
    kvstore:
      store: inmemory
