// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"user-service/internal/model"
)

type AuthPayload struct {
	Token string      `json:"token"`
	User  *model.User `json:"user"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}
